import type { Supplier, TrustScore } from "./types";

/**
 * داده‌ی نمایشی تا آماده‌شدن بک‌اند (افزایش ۲).
 * ساختار امتیازها دقیقاً با خروجی موتور Trust Score بک‌اند یکی است.
 */

function score(
  trust: number,
  risk: number,
  reliability: number,
  quality: number,
  onTime: number,
  satisfaction: number,
  responseHours: number,
): TrustScore {
  return {
    trust,
    risk,
    reliability,
    quality,
    components: [
      {
        key: "on_time_delivery",
        label: "تحویل به‌موقع",
        value: Math.round(onTime * 100),
        weight: 0.25,
        explanation: `${Math.round(onTime * 100)}٪ سفارش‌ها در موعد مقرر تحویل شده است`,
      },
      {
        key: "quality",
        label: "کیفیت",
        value: quality,
        weight: 0.25,
        explanation: "میانگین امتیاز کیفیت گزارش‌های QC و بازخورد خریداران",
      },
      {
        key: "satisfaction",
        label: "رضایت مشتری",
        value: satisfaction,
        weight: 0.2,
        explanation: "میانگین امتیاز نظرات تأییدشده‌ی خریداران",
      },
      {
        key: "response_speed",
        label: "سرعت پاسخ‌گویی",
        value: Math.max(0, Math.round(100 - responseHours * 8)),
        weight: 0.15,
        explanation: `میانگین زمان پاسخ به استعلام: ${responseHours} ساعت`,
      },
      {
        key: "dispute_history",
        label: "سابقه‌ی اختلاف",
        value: 100 - risk,
        weight: 0.15,
        explanation: "بدون اختلاف باز در ۱۲ ماه گذشته",
      },
    ],
  };
}

export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: "sup-1001",
    companyName: "صنایع دقیق‌تراش آریا",
    description:
      "ماشین‌کاری CNC قطعات فلزی با دقت بالا، تخصص در قطعات خودرویی و نفت و گاز. ۱۸ سال سابقه.",
    city: "تهران",
    address: "شهرک صنعتی شمس‌آباد",
    foundedYear: 1387,
    employeeCount: 45,
    capabilities: ["cnc", "tooling", "heat_treatment"],
    machines: [
      { name: "مرکز ماشین‌کاری ۵ محور", model: "DMG MORI DMU 50", count: 2 },
      { name: "تراش CNC", model: "Doosan Lynx 2100", count: 6 },
      { name: "فرز CNC", model: "Haas VF-4", count: 4 },
    ],
    certifications: [
      { title: "ISO 9001:2015", issuer: "TUV Nord", validUntil: "2027-03-01" },
      { title: "IATF 16949", issuer: "DQS", validUntil: "2026-11-15" },
    ],
    productionCapacityPerMonth: 12000,
    leadTimeDays: 14,
    completedJobs: 312,
    onTimeDeliveryRate: 0.96,
    responseTimeHours: 2,
    verified: true,
    score: score(92, 8, 94, 91, 0.96, 93, 2),
    galleryTitles: [
      "فلنج استیل ۳۰۴",
      "شفت CNC فولادی",
      "بوش برنجی",
      "قطعه‌ی ۵ محور آلومینیوم",
      "چرخ‌دنده‌ی مارپیچ",
      "نازل نفت و گاز",
    ],
  },
  {
    id: "sup-1002",
    companyName: "قالب‌سازان پیشرو اصفهان",
    description:
      "طراحی و ساخت قالب تزریق پلاستیک و دایکاست، تولید انبوه قطعات پلیمری صنعتی و خانگی.",
    city: "اصفهان",
    foundedYear: 1380,
    employeeCount: 80,
    capabilities: ["injection_molding", "tooling", "plastic_manufacturing"],
    machines: [
      { name: "تزریق پلاستیک ۴۰۰ تن", model: "Haitian MA4000", count: 5 },
      { name: "تزریق پلاستیک ۱۲۰ تن", model: "Haitian MA1200", count: 8 },
      { name: "وایرکات", model: "Sodick AQ400L", count: 2 },
    ],
    certifications: [
      { title: "ISO 9001:2015", issuer: "SGS", validUntil: "2026-09-20" },
    ],
    productionCapacityPerMonth: 500000,
    leadTimeDays: 30,
    completedJobs: 198,
    onTimeDeliveryRate: 0.91,
    responseTimeHours: 5,
    verified: true,
    score: score(85, 13, 88, 86, 0.91, 88, 5),
    galleryTitles: [
      "قالب دو حفره‌ای بدنه",
      "قطعات ABS تولید انبوه",
      "قالب دایکاست آلومینیوم",
      "درپوش POM",
    ],
  },
  {
    id: "sup-1003",
    companyName: "ورق‌کاران صنعت تبریز",
    description:
      "برش لیزر، خم CNC و جوشکاری ورق فولادی و استیل. سازنده‌ی بدنه‌ی تابلو برق و شاسی دستگاه.",
    city: "تبریز",
    foundedYear: 1392,
    employeeCount: 25,
    capabilities: ["sheet_metal", "welding", "surface_treatment"],
    machines: [
      { name: "برش لیزر فایبر ۶ کیلووات", model: "Bodor P3015", count: 1 },
      { name: "پرس برک CNC", model: "Yawei PBH 110", count: 2 },
    ],
    certifications: [
      { title: "گواهی جوش EN 1090", issuer: "TUV Austria" },
    ],
    productionCapacityPerMonth: 8000,
    leadTimeDays: 10,
    completedJobs: 145,
    onTimeDeliveryRate: 0.88,
    responseTimeHours: 3,
    verified: true,
    score: score(81, 17, 84, 80, 0.88, 84, 3),
  },
  {
    id: "sup-1004",
    companyName: "ریخته‌گری مدرن مشهد",
    description:
      "ریخته‌گری چدن و آلومینیوم به روش ماسه‌ای و دایکاست، همراه با ماشین‌کاری نهایی.",
    city: "مشهد",
    foundedYear: 1375,
    employeeCount: 110,
    capabilities: ["casting", "cnc", "heat_treatment"],
    machines: [
      { name: "خط قالب‌گیری اتوماتیک", model: "DISA 130", count: 1 },
      { name: "دایکاست ۸۰۰ تن", model: "Toshiba DC800", count: 2 },
    ],
    certifications: [
      { title: "ISO 9001:2015", issuer: "IMQ", validUntil: "2027-01-10" },
      { title: "ISO 14001", issuer: "IMQ" },
    ],
    productionCapacityPerMonth: 200000,
    leadTimeDays: 25,
    completedJobs: 421,
    onTimeDeliveryRate: 0.93,
    responseTimeHours: 8,
    verified: true,
    score: score(87, 11, 90, 89, 0.93, 90, 8),
  },
  {
    id: "sup-1005",
    companyName: "تراشکاری امید قم",
    description: "تراشکاری و فرزکاری قطعات سفارشی در تیراژ پایین، نمونه‌سازی سریع.",
    city: "قم",
    foundedYear: 1398,
    employeeCount: 8,
    capabilities: ["cnc", "welding"],
    machines: [
      { name: "تراش CNC", model: "TAKISAWA EX-110", count: 2 },
      { name: "فرز دستی", model: "تبریز FP4M", count: 3 },
    ],
    certifications: [],
    productionCapacityPerMonth: 2000,
    leadTimeDays: 7,
    completedJobs: 67,
    onTimeDeliveryRate: 0.82,
    responseTimeHours: 1,
    verified: false,
    score: score(72, 26, 75, 70, 0.82, 78, 1),
  },
  {
    id: "sup-1006",
    companyName: "پلیمر صنعت ساوه",
    description:
      "تولید قطعات پلاستیکی صنعتی با تزریق و اکستروژن، کامپاندهای مهندسی PA و POM.",
    city: "ساوه",
    foundedYear: 1385,
    employeeCount: 60,
    capabilities: ["plastic_manufacturing", "injection_molding"],
    machines: [
      { name: "تزریق ۲۵۰ تن", model: "JonWai TTI-250", count: 6 },
      { name: "خط اکستروژن", model: "Jwell JWS-65", count: 2 },
    ],
    certifications: [
      { title: "ISO 9001:2015", issuer: "BRS", validUntil: "2026-08-05" },
    ],
    productionCapacityPerMonth: 300000,
    leadTimeDays: 20,
    completedJobs: 234,
    onTimeDeliveryRate: 0.9,
    responseTimeHours: 6,
    verified: true,
    score: score(83, 15, 86, 84, 0.9, 86, 6),
  },
  {
    id: "sup-1007",
    companyName: "فورج فولاد اراک",
    description:
      "آهنگری گرم قطعات فولادی تا ۵۰ کیلوگرم، فلنج، شفت و قطعات راه‌سازی با عملیات حرارتی.",
    city: "اراک",
    foundedYear: 1370,
    employeeCount: 150,
    capabilities: ["forging", "heat_treatment", "cnc"],
    machines: [
      { name: "پرس فورج ۱۶۰۰ تن", model: "SMERAL LZK 1600", count: 1 },
      { name: "کوره‌ی القایی", model: "Inductotherm 500kW", count: 3 },
    ],
    certifications: [
      { title: "ISO 9001:2015", issuer: "TUV Nord", validUntil: "2027-06-01" },
      { title: "API Q1", issuer: "API" },
    ],
    productionCapacityPerMonth: 50000,
    leadTimeDays: 35,
    completedJobs: 502,
    onTimeDeliveryRate: 0.95,
    responseTimeHours: 12,
    verified: true,
    score: score(90, 9, 93, 92, 0.95, 91, 12),
  },
  {
    id: "sup-1008",
    companyName: "آبکاری کروم قزوین",
    description:
      "پوشش‌دهی سخت‌کروم، نیکل و گالوانیزه‌ی قطعات صنعتی، آماده‌سازی سطح و پولیش.",
    city: "قزوین",
    foundedYear: 1390,
    employeeCount: 18,
    capabilities: ["surface_treatment"],
    machines: [
      { name: "خط آبکاری اتوماتیک", model: "سفارشی ۱۲ وان", count: 1 },
    ],
    certifications: [],
    productionCapacityPerMonth: 15000,
    leadTimeDays: 5,
    completedJobs: 89,
    onTimeDeliveryRate: 0.85,
    responseTimeHours: 4,
    verified: false,
    score: score(74, 24, 78, 73, 0.85, 80, 4),
  },
];
